# This is the original answers file which was retrieved after the first installation.

# Format:
# <classname>: false - don't include this class
# <classname>: true - include and use the defaults
# <classname>:
#   <param>: <value> - include and override the default(s)
#
# See params.pp in each class for what options are available

---
foreman:
  foreman_url: https://foreman.r0ckhq.com
  puppetrun: false
  unattended: true
  unattended_url: 
  authentication: 
  passenger: true
  passenger_ruby: /usr/bin/tfm-ruby
  passenger_ruby_package: tfm-rubygem-passenger-native
  plugin_prefix: tfm-rubygem-foreman_
  servername: foreman.r0ckhq.com
  serveraliases:
  - foreman
  ssl: false
  repo: 
  configure_epel_repo: false
  configure_scl_repo: true
  selinux: 
  gpgcheck: true
  version: present
  plugin_version: present
  db_manage: true
  db_type: postgresql
  db_adapter: 
  db_host: 
  db_port: 
  db_database: 
  db_username: foreman
  db_password: MDkT3I66MESrvotdeTgB
  db_sslmode: 
  db_root_cert: 
  db_pool: 5
  db_manage_rake: true
  app_root: /usr/share/foreman
  manage_user: true
  user: foreman
  group: foreman
  user_groups:
  - puppet
  rails_env: production
  locations_enabled: 
  organizations_enabled: 
  passenger_interface: 
  vhost_priority: '05'
  server_port: 80
  server_ssl_port: 443
  server_ssl_ca: /etc/puppetlabs/puppet/ssl/certs/ca.pem
  server_ssl_chain: /etc/puppetlabs/puppet/ssl/certs/ca.pem
  server_ssl_cert: /etc/puppetlabs/puppet/ssl/certs/foreman.r0ckhq.com.pem
  server_ssl_certs_dir: ''
  server_ssl_key: /etc/puppetlabs/puppet/ssl/private_keys/foreman.r0ckhq.com.pem
  server_ssl_crl: /etc/puppetlabs/puppet/ssl/crl.pem
  server_ssl_protocol: 
  client_ssl_ca: /etc/puppetlabs/puppet/ssl/certs/ca.pem
  client_ssl_cert: /etc/puppetlabs/puppet/ssl/certs/foreman.r0ckhq.com.pem
  client_ssl_key: /etc/puppetlabs/puppet/ssl/private_keys/foreman.r0ckhq.com.pem
  keepalive: true
  max_keepalive_requests: 100
  keepalive_timeout: 5
  oauth_active: false
  oauth_map_users: false
  oauth_consumer_key: MLKTSU2RU7VbaUgM5XNfIw3RIF6TfbBS
  oauth_consumer_secret: dxo9rwZLN8w6gyrDzP2bjbWffztb2yvf
  passenger_prestart: true
  passenger_min_instances: 1
  passenger_start_timeout: 90
  initial_admin_username: admin
  initial_admin_password: ZQVK9v7LaPpsaM5ZXKVE
  initial_admin_first_name: Peter
  initial_admin_last_name: R0ck
  initial_admin_email: 
  initial_organization: 
  initial_location: 
  ipa_authentication: false
  http_keytab: /etc/httpd/conf/http.keytab
  pam_service: foreman
  ipa_manage_sssd: true
  websockets_encrypt: true
  websockets_ssl_key: /etc/puppetlabs/puppet/ssl/private_keys/.pem
  websockets_ssl_cert: /etc/puppetlabs/puppet/ssl/certs/foreman.r0ckhq.com.pem
  logging_level: info
  logging_type: file
  logging_layout: pattern
  loggers: {}
  email_delivery_method: 
  email_smtp_address: 
  email_smtp_port: 25
  email_smtp_domain: 
  email_smtp_authentication: none
  email_smtp_user_name: 
  email_smtp_password: 
  telemetry_prefix: fm_rails
  telemetry_prometheus_enabled: false
  telemetry_statsd_enabled: false
  telemetry_statsd_host: 127.0.0.1:8125
  telemetry_statsd_protocol: statsd
  telemetry_logger_enabled: false
  telemetry_logger_level: DEBUG
  dynflow_pool_size: 5
  jobs_service: dynflowd
  jobs_service_ensure: running
  jobs_service_enable: true
  hsts_enabled: true
  cors_domains: []
foreman::cli:
  foreman_url: 
  version: installed
  manage_root_config: true
  username: 
  password: 
  refresh_cache: false
  request_timeout: 120
  ssl_ca_file: 
  hammer_plugin_prefix: tfm-rubygem-hammer_cli_
foreman::cli::ansible: false
foreman::cli::discovery: false
foreman::cli::kubevirt: false
foreman::cli::openscap: false
foreman::cli::remote_execution: false
foreman::cli::tasks: false
foreman::cli::templates: false
foreman_proxy:
  repo: 
  gpgcheck: true
  version: present
  ensure_packages_version: present
  plugin_version: installed
  bind_host:
  - '::'
  http_port: 8000
  ssl_port: 8443
  dir: /usr/share/foreman-proxy
  user: foreman-proxy
  groups: []
  log: /var/log/foreman-proxy/proxy.log
  log_level: INFO
  log_buffer: 2000
  log_buffer_errors: 1000
  http: false
  ssl: true
  ssl_ca: /etc/puppetlabs/puppet/ssl/certs/ca.pem
  ssl_cert: /etc/puppetlabs/puppet/ssl/certs/foreman.r0ckhq.com.pem
  ssl_key: /etc/puppetlabs/puppet/ssl/private_keys/foreman.r0ckhq.com.pem
  foreman_ssl_ca: 
  foreman_ssl_cert: 
  foreman_ssl_key: 
  trusted_hosts:
  - foreman.r0ckhq.com
  ssl_disabled_ciphers: []
  tls_disabled_versions: []
  manage_sudoersd: true
  use_sudoersd: true
  use_sudoers: true
  puppetca: true
  puppetca_split_configs: true
  puppetca_listen_on: https
  ssldir: /etc/puppetlabs/puppet/ssl
  puppetdir: /etc/puppetlabs/puppet
  puppetca_cmd: /opt/puppetlabs/bin/puppet cert
  puppet_group: puppet
  puppetca_provider: puppetca_hostname_whitelisting
  autosignfile: /etc/puppetlabs/puppet/autosign.conf
  puppetca_sign_all: false
  puppetca_tokens_file: /var/lib/foreman-proxy/tokens.yml
  puppetca_token_ttl: 360
  puppetca_certificate: 
  manage_puppet_group: true
  puppet: true
  puppet_listen_on: https
  puppetrun_provider: 
  customrun_cmd: /bin/false
  customrun_args: -ay -f -s
  mcollective_user: root
  puppetssh_sudo: false
  puppetssh_command: /opt/puppetlabs/bin/puppet agent --onetime --no-usecacheonfailure
  puppetssh_user: root
  puppetssh_keyfile: /etc/foreman-proxy/id_rsa
  puppetssh_wait: false
  salt_puppetrun_cmd: puppet.run
  puppet_user: root
  puppet_url: https://foreman.r0ckhq.com:8140
  puppet_ssl_ca: /etc/puppetlabs/puppet/ssl/certs/ca.pem
  puppet_ssl_cert: /etc/puppetlabs/puppet/ssl/certs/foreman.r0ckhq.com.pem
  puppet_ssl_key: /etc/puppetlabs/puppet/ssl/private_keys/foreman.r0ckhq.com.pem
  puppet_api_timeout: 30
  templates: false
  templates_listen_on: both
  template_url: http://foreman.r0ckhq.com:8000
  logs: true
  logs_listen_on: https
  httpboot: 
  httpboot_listen_on: both
  tftp: true
  tftp_listen_on: https
  tftp_managed: true
  tftp_manage_wget: true
  tftp_syslinux_filenames:
  - /usr/share/syslinux/chain.c32
  - /usr/share/syslinux/mboot.c32
  - /usr/share/syslinux/menu.c32
  - /usr/share/syslinux/memdisk
  - /usr/share/syslinux/pxelinux.0
  tftp_root: /var/lib/tftpboot
  tftp_dirs:
  - /var/lib/tftpboot/pxelinux.cfg
  - /var/lib/tftpboot/grub
  - /var/lib/tftpboot/grub2
  - /var/lib/tftpboot/boot
  - /var/lib/tftpboot/ztp.cfg
  - /var/lib/tftpboot/poap.cfg
  tftp_servername: 
  tftp_replace_grub2_cfg: false
  dhcp: false
  dhcp_listen_on: https
  dhcp_managed: true
  dhcp_provider: isc
  dhcp_subnets: []
  dhcp_option_domain:
  - r0ckhq.com
  dhcp_search_domains: 
  dhcp_interface: ens192
  dhcp_additional_interfaces: []
  dhcp_gateway: 
  dhcp_range: 
  dhcp_pxeserver: 
  dhcp_pxefilename: pxelinux.0
  dhcp_network: 
  dhcp_netmask: 
  dhcp_nameservers: default
  dhcp_server: 127.0.0.1
  dhcp_config: /etc/dhcp/dhcpd.conf
  dhcp_leases: /var/lib/dhcpd/dhcpd.leases
  dhcp_key_name: 
  dhcp_key_secret: 
  dhcp_omapi_port: 7911
  dhcp_peer_address: 
  dhcp_node_type: standalone
  dhcp_failover_address: 10.93.216.45
  dhcp_failover_port: 519
  dhcp_max_response_delay: 30
  dhcp_max_unacked_updates: 10
  dhcp_mclt: 300
  dhcp_load_split: 255
  dhcp_load_balance: 3
  dhcp_manage_acls: true
  dns: false
  libvirt_network: default
  libvirt_connection: qemu:///system
  bmc: false
  bmc_listen_on: https
  bmc_default_provider: ipmitool
  bmc_ssh_user: root
  bmc_ssh_key: /usr/share/foreman/.ssh/id_rsa
  bmc_ssh_powerstatus: 'true'
  bmc_ssh_powercycle: shutdown -r +1
  bmc_ssh_poweroff: shutdown +1
  bmc_ssh_poweron: 'false'
  realm: false
  realm_listen_on: https
  realm_provider: freeipa
  realm_keytab: /etc/foreman-proxy/freeipa.keytab
  realm_principal: realm-proxy@EXAMPLE.COM
  freeipa_config: /etc/ipa/default.conf
  freeipa_remove_dns: true
  keyfile: /etc/rndc.key
  register_in_foreman: true
  foreman_base_url: https://foreman.r0ckhq.com
  registered_name: foreman.r0ckhq.com
  registered_proxy_url: 
  oauth_effective_user: admin
  oauth_consumer_key: MLKTSU2RU7VbaUgM5XNfIw3RIF6TfbBS
  oauth_consumer_secret: dxo9rwZLN8w6gyrDzP2bjbWffztb2yvf
puppet:
  version: present
  user: puppet
  group: puppet
  dir: /etc/puppetlabs/puppet
  codedir: /etc/puppetlabs/code
  vardir: /opt/puppetlabs/puppet/cache
  logdir: /var/log/puppetlabs/puppet
  rundir: /var/run/puppetlabs
  ssldir: /etc/puppetlabs/puppet/ssl
  sharedir: /opt/puppetlabs/puppet
  manage_packages: true
  dir_owner: root
  dir_group: 
  package_provider: 
  package_source: 
  port: 8140
  listen: false
  listen_to: []
  pluginsync: true
  splay: false
  splaylimit: 1800
  autosign: /etc/puppetlabs/puppet/autosign.conf
  autosign_entries: []
  autosign_mode: '0664'
  autosign_content: 
  autosign_source: 
  runinterval: 1800
  usecacheonfailure: true
  runmode: service
  run_hour: 
  run_minute: 
  unavailable_runmodes: []
  cron_cmd: 
  systemd_cmd: 
  systemd_randomizeddelaysec: 0
  agent_noop: false
  show_diff: false
  module_repository: 
  http_connect_timeout: 
  http_read_timeout: 
  ca_server: 
  ca_port: 
  ca_crl_filepath: 
  prerun_command: 
  postrun_command: 
  dns_alt_names: []
  use_srv_records: false
  srv_domain: r0ckhq.com
  pluginsource: puppet:///plugins
  pluginfactsource: puppet:///pluginfacts
  additional_settings: {}
  agent_additional_settings: {}
  agent_restart_command: /usr/bin/systemctl reload-or-restart puppet
  classfile: $statedir/classes.txt
  hiera_config: $confdir/hiera.yaml
  auth_template: puppet/auth.conf.erb
  allow_any_crl_auth: false
  auth_allowed:
  - $1
  client_package:
  - puppet-agent
  agent: true
  remove_lock: true
  report: true
  client_certname: foreman.r0ckhq.com
  puppetmaster: 
  systemd_unit_name: puppet-run
  service_name: puppet
  syslogfacility: 
  environment: production
  server: true
  server_admin_api_whitelist:
  - localhost
  - foreman.r0ckhq.com
  server_manage_user: true
  server_user: puppet
  server_group: puppet
  server_dir: /etc/puppetlabs/puppet
  server_ip: 0.0.0.0
  server_port: 8140
  server_ca: true
  server_ca_crl_sync: false
  server_crl_enable: 
  server_ca_auth_required: true
  server_ca_client_whitelist:
  - localhost
  - foreman.r0ckhq.com
  server_custom_trusted_oid_mapping: 
  server_http: false
  server_http_port: 8139
  server_reports: foreman
  server_puppetserver_dir: /etc/puppetlabs/puppetserver
  server_puppetserver_vardir: /opt/puppetlabs/server/data/puppetserver
  server_puppetserver_rundir: /var/run/puppetlabs/puppetserver
  server_puppetserver_logdir: /var/log/puppetlabs/puppetserver
  server_puppetserver_version: 
  server_external_nodes: /etc/puppetlabs/puppet/node.rb
  server_cipher_suites:
  - TLS_RSA_WITH_AES_256_CBC_SHA256
  - TLS_RSA_WITH_AES_256_CBC_SHA
  - TLS_RSA_WITH_AES_128_CBC_SHA256
  - TLS_RSA_WITH_AES_128_CBC_SHA
  server_config_version: 
  server_connect_timeout: 120000
  server_git_repo: false
  server_default_manifest: false
  server_default_manifest_path: /etc/puppet/manifests/default_manifest.pp
  server_default_manifest_content: ''
  server_environments_owner: puppet
  server_environments_group: 
  server_environments_mode: '0755'
  server_envs_dir: /etc/puppetlabs/code/environments
  server_envs_target: 
  server_common_modules_path:
  - /etc/puppetlabs/code/environments/common
  - /etc/puppetlabs/code/modules
  - /opt/puppetlabs/puppet/modules
  - /usr/share/puppet/modules
  server_git_repo_mode: '0755'
  server_git_repo_path: /opt/puppetlabs/puppet/cache/puppet.git
  server_git_repo_group: puppet
  server_git_repo_user: puppet
  server_git_branch_map: {}
  server_idle_timeout: 1200000
  server_post_hook_content: puppet/server/post-receive.erb
  server_post_hook_name: post-receive
  server_storeconfigs_backend: 
  server_ruby_load_paths:
  - /opt/puppetlabs/puppet/lib/ruby/vendor_ruby
  server_ssl_dir: /etc/puppetlabs/puppet/ssl
  server_ssl_dir_manage: true
  server_ssl_key_manage: true
  server_ssl_protocols:
  - TLSv1.2
  server_ssl_chain_filepath: /etc/puppetlabs/puppet/ssl/ca/ca_crt.pem
  server_package: 
  server_version: 
  server_certname: foreman.r0ckhq.com
  server_enc_api: v2
  server_report_api: v2
  server_request_timeout: 60
  server_strict_variables: false
  server_additional_settings: {}
  server_foreman: true
  server_foreman_url: https://foreman.r0ckhq.com
  server_foreman_ssl_ca: 
  server_foreman_ssl_cert: 
  server_foreman_ssl_key: 
  server_foreman_facts: true
  server_puppet_basedir: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet
  server_puppetdb_host: 
  server_puppetdb_port: 8081
  server_puppetdb_swf: false
  server_parser: current
  server_environment_timeout: 
  server_jvm_java_bin: /usr/bin/java
  server_jvm_config: /etc/sysconfig/puppetserver
  server_jvm_min_heap_size: 2G
  server_jvm_max_heap_size: 2G
  server_jvm_extra_args: 
  server_jvm_cli_args: 
  server_jruby_gem_home: /opt/puppetlabs/server/data/puppetserver/jruby-gems
  server_max_active_instances: 4
  server_max_requests_per_instance: 0
  server_max_queued_requests: 0
  server_max_retry_delay: 1800
  server_use_legacy_auth_conf: false
  server_check_for_updates: true
  server_environment_class_cache_enabled: false
  server_allow_header_cert_info: false
  server_web_idle_timeout: 30000
  server_puppetserver_jruby9k: false
  server_puppetserver_metrics: 
  server_metrics_jmx_enable: true
  server_metrics_graphite_enable: false
  server_metrics_graphite_host: 127.0.0.1
  server_metrics_graphite_port: 2003
  server_metrics_server_id: foreman.r0ckhq.com
  server_metrics_graphite_interval: 5
  server_metrics_allowed: 
  server_puppetserver_experimental: true
  server_puppetserver_trusted_agents: []
  server_compile_mode: 
  server_acceptor_threads: 
  server_selector_threads: 
  server_ssl_acceptor_threads: 
  server_ssl_selector_threads: 
  server_max_threads: 
  server_ca_allow_sans: false
  server_ca_allow_auth_extensions: false
  server_ca_enable_infra_crl: false
  server_max_open_files: 
foreman::plugin::ansible: false
foreman::plugin::azure: false
foreman::plugin::bootdisk: false
foreman::plugin::chef: false
foreman::plugin::cockpit: false
foreman::plugin::default_hostgroup: false
foreman::plugin::dhcp_browser: false
foreman::plugin::digitalocean: false
foreman::plugin::discovery: false
foreman::plugin::expire_hosts: false
foreman::plugin::hooks: false
foreman::plugin::host_extra_validator: false
foreman::plugin::kubevirt: false
foreman::plugin::memcache: false
foreman::plugin::monitoring: false
foreman::plugin::omaha: false
foreman::plugin::openscap: false
foreman::plugin::ovirt_provision: false
foreman::plugin::puppetdb: false
foreman::plugin::remote_execution: false
foreman::plugin::salt: false
foreman::plugin::setup: false
foreman::plugin::snapshot_management: false
foreman::plugin::tasks: false
foreman::plugin::templates: false
foreman::compute::ec2: false
foreman::compute::gce: false
foreman::compute::libvirt: false
foreman::compute::openstack: false
foreman::compute::ovirt: false
foreman::compute::rackspace: false
foreman::compute::vmware: false
foreman_proxy::plugin::ansible: false
foreman_proxy::plugin::chef: false
foreman_proxy::plugin::dhcp::infoblox: false
foreman_proxy::plugin::dhcp::remote_isc: false
foreman_proxy::plugin::discovery: false
foreman_proxy::plugin::dns::infoblox: false
foreman_proxy::plugin::dns::powerdns: false
foreman_proxy::plugin::dynflow: false
foreman_proxy::plugin::monitoring: false
foreman_proxy::plugin::omaha: false
foreman_proxy::plugin::openscap: false
foreman_proxy::plugin::pulp: false
foreman_proxy::plugin::remote_execution::ssh: false
foreman_proxy::plugin::salt: false