---
- hosts: workstations
  become: true

  roles: 
    - environment
    - packages
    - foreman-install

- hosts: workstations
  become: true
  vars:
    reboot: false
  roles:
    - reboot
  tags: 
    - reboot
